flask_pymongo/__init__.py
You get a rather cryptic error when the `MONGO_URI` config value is missing a database path because `uri_parser.parse_uri(app.config[key'URI'])` returns `{…, "database": None, …}` and `PyMongo.init_app(…)` only checks for the non-existence of the `"database"` key.
This patch fixes that.
=> Ensure error is raised when URI database name is parsed as 'None'.

requirements.txt
Since the 3.0 version of pymongo has broke the tests due to many backward compatibilty breaks, the fastest solution till all the corrections are in place is to force the pymongo version to 2.7 max
=> update requirements for pymongo

examples/wiki/wiki.py, flask_pymongo/__init__.py, flask_pymongo/wrappers.py, requirements.txt, tests/test_config.py, tests/test_wrappers.py
This pull request is an attempt of enabling the use of pymongo >= 3.0.
In `__init__.py` and the test files there are explicit tests whether pymongo >= 3.0 is used, which is ugly, but I have deemed it necessary to bridge the deprecation problems.
Modifications:
* Removed `auto_start_request` from __init__ in the pymongo >= 3.0 case.
* Using only the `MongoClient` for pymongo >= 3.0 case, since `MongoReplicaSetClient` is labelled deprecated and all functionality has been merged to `MongoClient`.
* Wrappers has a overriding `__getitem__` method added. In pymongo < 3.0 the `__getitem__` method (used when calling `c[db_name]`) called the `__getattr__` method (used when calling `c.db_name`), so wrappers did not need to override both then. In pymongo > 3.0 this is not the case and both have to …
=> Modifications to enable pymongo 3.0.x compatability.

docs/index.rst, flask_pymongo/__init__.py
Fixes #66
When using PyMongo >= 3.0 in a [multiprocessing](https://api.mongodb.org/python/current/faq.html#multiprocessing) setup, one might have to initialize the MongoClient with `connect=False` keyword. This pull requests adds such a setting.
=> Added MONGO_CONNECT option at app init.

tests/test_config.py, tests/test_url_converter.py, tests/test_wrappers.py
When trying to install this module in a global namespace, 'tests' is installed as a separate module that conflicts with other packages (if they have the same problem).
There are different ways to avoid this, but I'm trying the easy approach, and sending a pull request to see if the tests will still run in travis.
=> Delete __init__.py in tests directory

examples/wiki/wiki.py
I brought this up a WHILE ago in an issue - https://github.com/dcrosta/flask-pymongo/issues/44
Finally remembered to fix it.
=> Solves the url redirect rule problem

README.md, examples/wiki/wiki.py
updated example and quickstart in readme to import with flask_pymongo instead.
=> issue #84 Importing flask.ext.pymongo is deprecated, use flask_pymongo instead.

flask_pymongo/__init__.py
https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/common.py#L465
Based on this mapping, we can see that pymongo lowercase the keyword and is not adding underscore
=> set correct options from mongo uri parsed by pymongo

docs/index.rst, flask_pymongo/__init__.py, requirements.txt
This is a follow up to #36 to hopefully close out #34 
I think this would also necessitate a version bump to flask-pymongo but will let the maintainer make that decision
=> Adding support for auth source and auth mechanism

flask_pymongo/__init__.py
I actually happened to make what I believe is a fix for #77 yesterday: In PyMongo>=3.0, the parameter max_pool_size is renamed maxPoolSize, which will lead to that very problem.
I was making some modifications to fit another issue and did this as well.
=> Max_pool_size renamed maxPoolSize in pymongo>=3.0

.travis.yml, flask_pymongo/__init__.py, tests/test_config.py
Sets default AUTH_MECHANISM values when using non URI configuration method.
Without this, trying to configure pymongo using a configuration prefix causes a KeyError
(Now with added tests)
=> Default AUTH_MECHANISM

.gitignore, flask_pymongo/__init__.py, tests/test_url_converter.py
http://flask-pymongo.readthedocs.io/en/latest/#flask_pymongo.BSONObjectIdConverter
Moreover, I think it's more consistent to return a 404 than a 400 in such situation.
=> according to the docs, this should be a 404

flask_pymongo/__init__.py
According to http://flask.pocoo.org/docs/1.0/extensiondev/
> The `__init__` method takes an optional app object and, if supplied, will
call `init_app`.
=> Fix broken flask extension interface.

README.md
If someone run the quickstart sample equal to the example, will be fail, because render_template is not imported.
=> Fix quickstart example

docs/index.rst, flask_pymongo/__init__.py, flask_pymongo/helpers.py, flask_pymongo/tests/test_json.py, setup.py
=> Add `jsonify()` support using PyMongo's `bson.json_util`

azure-pipelines.yml, docs/index.rst, setup.py, tox.ini
Eventually this will close #127; but we'll wait until the official 4.2 series is released (currently it's in RC) and available in Docker hub.
=> test matrix: added mongo 4.2, pymongo 3.9, flask 1.1; removed flask 0.11, python 3.4

docs/index.rst, flask_pymongo/helpers.py
There are small typos in:
- docs/index.rst
- flask_pymongo/helpers.py
Fixes:
- Should read `instance` rather than `instnace`.
- Should read `recognized` rather than `recignozed`.
- Should read `constants` rather than `contants`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

flask_pymongo/__init__.py
This PR will wrap the `MongoClient` creation with [`pymongo.driver_info.DriverInfo`](https://pymongo.readthedocs.io/en/stable/api/pymongo/driver_info.html#pymongo.driver_info.DriverInfo) which makes it easier to filter `mongod` logs for connections that originate from Flask-PyMongo.
For example:
> {"t":{"$date":"2024-06-03T16:10:26.686-04:00"},"s":"I","c":"NETWORK","id":51800,"ctx":"conn225","msg":"client metadata","attr":{"remote":"127.0.0.1:61857","client":"conn225","negotiatedCompressors":[],"doc":{"driver":{"name":"PyMongo|Flask-PyMongo","version":"3.11.4|2.3.1"},"os":{"type":"Darwin","name":"Darwin","architecture":"x86_64","version":"14.5"},"platform":"CPython 3.10.3.final.0"}}}
=> Add DriverInfo to MongoClient creation

flask_pymongo/__init__.py
Some times file name not set in request. It is better to set it explicitly.
=> file_name_in_send_file

docs/conf.py, examples/wiki/wiki.py, flask_pymongo/__init__.py, flask_pymongo/helpers.py, flask_pymongo/wrappers.py, justfile, pyproject.toml, tests/test_config.py, tests/test_gridfs.py, tests/test_json.py, tests/test_url_converter.py, tests/test_wrappers.py, tests/util.py, uv.lock
=> INTPYTHON-380 Add typing

flask_pymongo/__init__.py, tests/test_gridfs.py
=> Add support for db in GridFS functions

.github/workflows/test-python.yml
Run tests against minimum python packages and supported MongoDB version.  Also test against the latest MongoDB version.
=> Add tests for min dependencies and update test matrix for min and max server versions

flask_pymongo/__init__.py, tests/test_gridfs.py, tests/util.py
=> Use caching for the etag using stored hash if available

.github/workflows/release-python.yml, .gitignore, CHANGELOG.md
Fixes #186.  Hatch was using the `.gitignore` file to determine which files to include in the dists.
=> Fix handling of _version.py file

.github/workflows/dist-python.yml, .github/workflows/release-python.yml
I couldn't claim the test pypi package, so I added a strict `twine` check instead.
Passing dry run build: https://github.com/mongodb-labs/flask-pymongo/actions/runs/14573288115
=> INTPYTHON-594 Add automated release workflow
